- hosts: console
  vars:
    hub_ver: 2.14.2
    rke_ver: v1.1.6
    kubectl_ver: v1.19.0
    calicoctl_ver: v3.15.2
    kubernetes_helm_ver: v3.3.0
    argocd_ver: v1.7.4
    go_ver: '1.15'
    hashi_apps:
      - name: terraform
        ver: 0.13.2
  roles:
    - role: andrewrothstein.hashi
    - role: andrewrothstein.hub
    - role: andrewrothstein.rke
    - role: andrewrothstein.kubectl
    - role: andrewrothstein.calicoctl
    - role: andrewrothstein.kubernetes-helm
    - role: andrewrothstein.argocd
    - role: andrewrothstein.go
    - role: andrewrothstein.k3d
