- hosts: console
  vars:
    hub_ver: 2.14.2
    rke_ver: v1.2.3
    kubectl_ver: v1.19.3
    calicoctl_ver: v3.17.0
    kubernetes_helm_ver: v3.4.1
    argocd_ver: v1.7.10
    go_ver: 1.15.5
    hashi_apps:
      - name: terraform
        ver: 0.13.5
      - name: packer
        ver: 1.6.4
    k3d_ver: v3.3.0
    k9s_ver: v0.24.1
  roles:
    - role: andrewrothstein.hashi
    - role: andrewrothstein.hub
    - role: andrewrothstein.rke
    - role: andrewrothstein.kubectl
    - role: andrewrothstein.calicoctl
    - role: andrewrothstein.kubernetes-helm
    - role: andrewrothstein.argocd
    - role: andrewrothstein.go
    - role: andrewrothstein.k3d
    - role: andrewrothstein.k9s
