---
- hosts: minio
  vars:
    minio_tls:
      enable: True
      pki_dir: '{{ pki_secrets_dir }}'
    minio_config:
      enable: True
      opts: --address 0.0.0.0:9000
      server_access_key: '{{ minio_access_key }}'
      server_secret_key: '{{ minio_secret_key }}'
      volumes:
        - /var/minio/data
    minio_alias: gitlab
    minio_buckets_to_create:
      - gitlab-artifacts
      - gitlab-externaldiffs
      - gitlab-lfs
      - gitlab-uploads
      - gitlab-dependencyproxy
      - gitlab-terraformstate
      - gitlab-runner-cache
      - vault-data
  roles:
    - role: andrewrothstein.minio
  tasks:
    - name: login mc
      command:
        cmd: /usr/local/bin/mc alias set {{ minio_alias }} https://gitlab.nj.drewfus.org:9000 {{ minio_access_key }} {{ minio_secret_key }}
    - name: creating minio buckets with mc
      with_items: '{{ minio_buckets_to_create }}'
      command:
        cmd: /usr/local/bin/mc mb --ignore-existing {{ minio_alias }}/{{ item }}
