---
- hosts: all
  roles:
    - role: andrewrothstein.sudoers
- hosts: san
  roles:
    - role: andrewrothstein.docker_engine
  tasks:
    - name: add arothste to docker group
      become: yes
      become_user: root
      user:
        name: arothste
        groups:
          - docker
        append: yes
    - name: install open iscsi initiator
      become: yes
      become_user: root
      package:
        name: open-iscsi
        state: present
    - name: start iscsid service
      become: yes
      become_user: root
      service:
        name: iscsid
        state: started
        enabled: true
- hosts:
    - vault
    - console
  roles:
    - role: andrewrothstein.hashi
      hashi_apps:
        - name: vault
          ver: 1.5.0
- hosts: console
  vars:
    hub_ver: 2.14.2
    rke_ver: v1.1.3
    kubectl_ver: v1.18.3
    calicoctl_ver: v3.14.1
    kubernetes_helm_ver: v3.2.1
    argocd_ver: v1.5.6
    go_ver: 1.14.4
  roles:
    - role: andrewrothstein.hub
    - role: andrewrothstein.rke
    - role: andrewrothstein.kubectl
    - role: andrewrothstein.calicoctl
    - role: andrewrothstein.kubernetes-helm
    - role: andrewrothstein.argocd
    - role: andrewrothstein.go
    - role: andrewrothstein.kind