---
- import_playbook: sudoers.yml
- import_playbook: trust-ca.yml
- import_playbook: san.yml
- import_playbook: docker.yml
- import_playbook: vault.yml
- import_playbook: gitlab.yml
- import_playbook: console.yml
