---
# ansible-playbook reboot.yml -e reboot_group=san
- hosts: '{{ reboot_group }}'
  tasks:
    - become: yes
      become_user: root
      reboot:
        reboot_timeout: '{{ reboot_timeout | default(3600) }}'
