---
- role: andrewrothstein.sudoers
  version: v1.0.12
- role: andrewrothstein.hub
  version: v1.0.23
- role: andrewrothstein.rke
  version: v1.0.8
- role: andrewrothstein.kubectl
  version: v1.1.39
- role: andrewrothstein.kubernetes-helm
  version: v1.3.10
- role: andrewrothstein.ceph
  version: v2.0.1
