---
- role: andrewrothstein.sudoers
  version: v1.0.12
- role: andrewrothstein.hub
  version: v1.0.23
- role: andrewrothstein.rke
  version: v1.0.12
- role: andrewrothstein.kubectl
  version: v1.1.44
- role: andrewrothstein.calicoctl
  version: v1.1.14
- role: andrewrothstein.kubernetes-helm
  version: v1.3.14
- role: andrewrothstein.docker_engine
  version: v0.0.2
- role: andrewrothstein.argocd
  version: v1.0.4
- role: andrewrothstein.pkg-upgrade
  version: v1.0.9
- role: andrewrothstein.hashi
  version: v0.2.0
- role: andrewrothstein.go
  version: v2.1.37
- role: andrewrothstein.k3d
  version: v1.0.3
- role: andrewrothstein.gitlab
  version: v1.3.3
