---
- role: andrewrothstein.sudoers
  version: v1.0.12
- role: andrewrothstein.hub
  version: v1.0.23
- role: andrewrothstein.rke
  version: v1.0.9
- role: andrewrothstein.kubectl
  version: v1.1.39
- role: andrewrothstein.kubernetes-helm
  version: v1.3.10
- role: andrewrothstein.docker_engine
  version: v0.0.2
- role: andrewrothstein.argocd
  version: v1.0.2
- role: andrewrothstein.pkg-upgrade
  version: v1.0.9
