---
- hosts: vault
  vars:
    vault_ver: 1.5.5
  roles:
    - role: andrewrothstein.vault-config
      vault_config_tls:
        enable: True
        pki_dir: '{{ pki_secrets_dir }}'
      vault_config_storage:
        ty: s3
        bucket: vault-data
        access_key: '{{ minio_access_key }}'
        secret_key: '{{ minio_secret_key }}'
        endpoint: http://127.0.0.1:9000
        s3_force_path_style: True
        disable_ssl: True
      vault_config_listeners:
        - ty: tcp
          address: 0.0.0.0:8200
          cluster_address: 0.0.0.0:8201
